In [2]:
from sklearn.cluster import AffinityPropagation
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])
clustering = AffinityPropagation().fit(X)
print(clustering)
print(clustering.labels_)
print(clustering.predict([[0, 0], [4, 4]]))
print(clustering.cluster_centers_)
print(clustering.cluster_centers_indices_)
print(clustering.affinity_matrix_)
print(clustering.n_iter_)

AffinityPropagation(affinity='euclidean', convergence_iter=15, copy=True,
                    damping=0.5, max_iter=200, preference=None, verbose=False)
[0 0 0 1 1 1]
[0 1]
[[1 2]
 [4 2]]
[0 3]
[[ -0.  -4.  -4.  -9. -13. -13.]
 [ -4.  -0. -16. -13.  -9. -25.]
 [ -4. -16.  -0. -13. -25.  -9.]
 [ -9. -13. -13.  -0.  -4.  -4.]
 [-13.  -9. -25.  -4.  -0. -16.]
 [-13. -25.  -9.  -4. -16.  -0.]]
16
