In [2]:
from sklearn.cluster import OPTICS
import numpy as np
X = np.array([[1, 2], [2, 5], [3, 6],
              [8, 7], [8, 8], [7, 3]])
clustering = OPTICS(min_samples=2).fit(X)
print(clustering.labels_)
print(clustering.reachability_)
print(clustering.ordering_)
print(clustering.core_distances_)
print(clustering.predecessor_)
print(clustering.cluster_hierarchy_)

[0 0 0 1 1 1]
[       inf 3.16227766 1.41421356 4.12310563 1.         5.        ]
[0 1 2 5 3 4]
[3.16227766 1.41421356 1.41421356 1.         1.         4.12310563]
[-1  0  1  5  3  2]
[[0 2]
 [3 5]
 [0 5]]
