## Numpy and Scipy

Compiled languages like Fortran and C are natively much faster than Python.
Using packages like Cython enables Python to interface with C code and pass information from the C program to Python and vice versa through memory. 

Powerhouses of scientific Python: NumPy and SciPy. Include arrays, matrices, integration, differential equation solvers, statistics, and much more.

SciPy is built on the NumPy array framework.Includes integration, ordinary differential equation solvers, special functions, optimizations, and more.





## Numpy

Capabilities of N-dimensional arrays, element-by-element operations (broadcasting), core mathematical operations like linear algebra, and the ability to wrap C/C++/Fortran code.

Overcome the shortcomings of the Python lists by providing a data storage
object called ndarray (similar to lists). But only the same type of element can be stored in each column. Operations are sped up significantly.





In [0]:
import numpy as np

In [0]:
# Create an array with 10^7 elements.
arr = np.arange(10)
print(arr)
# Converting ndarray to list
larr = arr.tolist()
print(larr)

[0 1 2 3 4 5 6 7 8 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
# Creating a 3D numpy array
arr = np.zeros((3,3,3))
print(arr)
# Trying to convert array to a matrix, which will not work.
# Since,matrix objects can and only will be two dimensional.
#mat = np.matrix(arr)
#print(mat)
#ValueError: shape too large to be a matrix.

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


## Array Creation and Data Typing




In [0]:

# Creating an array of zeros with five elements
arr = np.zeros(5)
print(arr)
# What if we want to create an array going from 0 to 100?
arr = np.arange(100)
# Or 10 to 100?
arr = np.arange(10,100)
# If you want 100 steps from 0 to 1...
arr = np.linspace(0, 1, 100)
# Or if you want to generate an array from 1 to 10
# in log10 space in 100 steps...
arr = np.logspace(0, 1, 100, base=10.0)
print(arr)
# Creating a 5x5 array of zeros (an image)
image = np.zeros((5,5))
print(image)
# Creating a 5x5x5 cube of 1's
# The astype() method sets the array with integer elements.
cube = np.zeros((5,5,5)).astype(int) + 1
print(cube)
# Or even simpler with 16-bit floating-point precision...
cube = np.ones((5, 5, 5)).astype(np.float16)
print(cube)

[0. 0. 0. 0. 0.]
[ 1.          1.02353102  1.04761575  1.07226722  1.09749877  1.12332403
  1.149757    1.17681195  1.20450354  1.23284674  1.26185688  1.29154967
  1.32194115  1.35304777  1.38488637  1.41747416  1.45082878  1.48496826
  1.51991108  1.55567614  1.59228279  1.62975083  1.66810054  1.70735265
  1.7475284   1.78864953  1.83073828  1.87381742  1.91791026  1.96304065
  2.009233    2.05651231  2.10490414  2.15443469  2.20513074  2.25701972
  2.3101297   2.36448941  2.42012826  2.47707636  2.53536449  2.59502421
  2.65608778  2.71858824  2.7825594   2.84803587  2.91505306  2.98364724
  3.05385551  3.12571585  3.19926714  3.27454916  3.35160265  3.43046929
  3.51119173  3.59381366  3.67837977  3.76493581  3.85352859  3.94420606
  4.03701726  4.1320124   4.22924287  4.32876128  4.43062146  4.53487851
  4.64158883  4.75081016  4.86260158  4.97702356  5.09413801  5.21400829
  5.33669923  5.46227722  5.59081018  5.72236766  5.85702082  5.9948425
  6.13590727  6.28029144  6.4280731

If you are working with 64-bit Python, then your elements in the arrays will
default to 64-bit precision (bit depth).

You can specify the bit depth when creating arrays by setting the data
type parameter (dtype) to int, numpy.float16, numpy.float32, or numpy.float64.



In [0]:
# Array of zero integers
arr = np.zeros(2, dtype=int)
print(arr)
# Array of zero floats
arr = np.zeros(2, dtype=np.float32)
print(arr)
# Identity matrix
my_matrx = np.eye(6) 
print(my_matrx)
#Array of 1s
data = np.ones(4)
print(data)

[0 0]
[0. 0.]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[1. 1. 1. 1.]


In [0]:
# First we create a list and then
# wrap it with the np.array() function.

alist = [1, 2, 3]       #vector of rows
arr = np.array(alist)
print(arr)

alist = [[1], [2], [3]]     #vector of columns
arr = np.array(alist)
print(arr)

A = np.matrix([[3, 6, -5],[1, -3, 2],[5, -1, 4]]) # Defining the matrices
print(A)

print(A.shape)  #View the Number of Rows and Columns
print(A.size)   #View the number of elements (rows*columns)
print(A.ndim)   #View the number of Dimensions(2 in this case)

#Return the max element
print(np.max(A))
#Return the min element
print(np.min(A))
#To find the max element in each column
print(np.max(A,axis=0))


[1 2 3]
[[1]
 [2]
 [3]]
[[ 3  6 -5]
 [ 1 -3  2]
 [ 5 -1  4]]
(3, 3)
9
2
6
-5
[[5 6 4]]
1.3333333333333333
3.496029493900505
12.222222222222221
[[ 3  1  5]
 [ 6 -3 -1]
 [-5  2  4]]
[[ 3 -3  4]]
[ 3.18270043+4.11426089j  3.18270043-4.11426089j -2.36540086+0.j        ]
[[-0.08235996+0.61456618j -0.08235996-0.61456618j  0.43391486+0.j        ]
 [ 0.20612063-0.03776147j  0.20612063+0.03776147j -0.77328937+0.j        ]
 [ 0.75605132+0.j          0.75605132-0.j         -0.46232181+0.j        ]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:37: RuntimeWarning: invalid value encountered in log


In [0]:
#Mean
print(np.mean(A))
#Standard Dev.
print(np.std(A))
#Variance
print(np.var(A))
np.exp(A)     #Returns the exponentials of each element
np.sin(A)     #Returns the sin of each element
np.cos(A)     #Returns the cosine of each element
np.log(A)     #Returns the logarithm of each element
np.sum(A)     #Returns the sum total of elements in the array

#Transpose the matrix
print(A.T)
#Print the Principal diagonal
print(A.diagonal())

# Calculate the Eigenvalues and Eigenvectors of that Matrix
eigenvalues ,eigenvectors=np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

In [0]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


Reshaping

In [0]:
# Creating an array with elements from 0 to 999
arr1d = np.arange(1000)
# Now reshaping the array to a 10x10x10 3D array
arr3d = arr1d.reshape((10,10,10))
# The reshape command can alternatively be called this way
arr3d = np.reshape(arr1d, (10, 10, 10))
# Inversely, we can flatten arrays
arr4d = np.zeros((10, 10, 10, 10))
arr1d = arr4d.ravel()

## Record Arrays

(Used for tables)
i4 corresponds to a 32-bit integer, f4 corresponds to a 32-bit float,
and a10 corresponds to a string 10 characters long.

In [0]:
# Creating an array of zeros and defining column types
recarr = np.zeros((2,), dtype=('i4,f4,a10'))
toadd = [(1,2.,'Hello'),(2,3.,"World")]
recarr[:] = toadd
print(recarr)

[(1, 2., b'Hello') (2, 3., b'World')]


Using rand to get random values from Gaussian distribution.

In [0]:
import numpy.random as rand
# Creating a 10-element array with random values
# from a standard normal distribution or, in other
# words, a Gaussian distribution.The sigma is 1 and the mean is 0.
a = rand.randn(10)
print(a)

#matrix
b = rand.randn(5,4)
print(b)

#random numbers
c=rand.rand(5)
print(c)

#one-dimensional array
d=rand.randint(5)
print(d)

#2d array
e=rand.randint(1,5)
print(e)

#include 1 exclude 5, 7 elements
f=rand.randint(1,5,7)
print(f)

[-0.671598   -1.31089843  0.09833863  0.89781582  0.17322363  0.23764341
 -2.32581065  1.91213906  1.36695549  0.3983347 ]
[[-0.72955911 -0.70226857 -1.31860294 -0.17498429]
 [ 0.62380195  0.03729828 -0.39791764  0.86985052]
 [ 1.74078972 -0.71808175  0.66264522  0.61321259]
 [-1.83810509  0.11505271  0.41933077 -1.28053009]
 [ 0.03834179  0.32516135 -0.65806199 -1.59921293]]
[0.97070236 0.43098225 0.64262098 0.9992781  0.83923251]
0
4
[2 3 2 3 3 1 1]


Read and Write Files

In [0]:
arr = np.loadtxt('somefile.txt')
np.savetxt('somenewfile.txt')

If each column is different in terms of formatting, loadtxt can still read the data, but the column types need to be predefined. 

In [0]:
# example.txt file looks like the following
#
# XR21 32.789 1
# XR22 33.091 2
table = np.loadtxt('example.txt',
dtype='names': ('ID', 'Result', 'Type'),
'formats': ('S4', 'f4', 'i2'))